In [1]:
import pandas as pd 
output = pd.read_csv("labels.csv")
input_data = pd.read_csv("values.csv")

In [2]:
input_data

patient_id  slope_of_peak_exercise_st_segment               thal  \
0       0z64un                                  1             normal   
1       ryoo3j                                  2             normal   
2       yt1s1x                                  1             normal   
3       l2xjde                                  1  reversible_defect   
4       oyt4ek                                  3  reversible_defect   
..         ...                                ...                ...   
175     5qfar3                                  2  reversible_defect   
176     2s2b1f                                  2             normal   
177     nsd00i                                  2  reversible_defect   
178     0xw93k                                  1             normal   
179     2nx10r                                  1             normal   

     resting_blood_pressure  chest_pain_type  num_major_vessels  \
0                       128                2                  0   
1                       110                3                  0   
2                       125                4                  3   
3                       152                4                  0   
4                       178                1                  0   
..                      ...              ...                ...   
175                     125                4                  2   
176                     180                4                  0   
177                     125                3                  0   
178                     124                3                  2   
179                     160                3                  1   

     fasting_blood_sugar_gt_120_mg_per_dl  resting_ekg_results  \
0                                       0                    2   
1                                       0                    0   
2                                       0                    2   
3                                       0                    0   
4                                       0                    2   
..                                    ...                  ...   
175                                     1                    0   
176                                     0                    1   
177                                     0                    0   
178                                     1                    0   
179                                     0                    0   

     serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression  sex  age  \
0                            308                       0.0    1   45   
1                            214                       1.6    0   54   
2                            304                       0.0    1   77   
3                            223                       0.0    1   40   
4                            270                       4.2    1   59   
..                           ...                       ...  ...  ...   
175                          254                       0.2    1   67   
176                          327                       3.4    0   55   
177                          309                       1.8    1   64   
178                          255                       0.0    1   48   
179                          201                       0.0    0   54   

     max_heart_rate_achieved  exercise_induced_angina  
0                        170                        0  
1                        158                        0  
2                        162                        1  
3                        181                        0  
4                        145                        0  
..                       ...                      ...  
175                      163                        0  
176                      117                        1  
177                      131                        1  
178                      175                        0  
179                      163                        0  

[18

In [3]:
output

patient_id  heart_disease_present
0       0z64un                      0
1       ryoo3j                      0
2       yt1s1x                      1
3       l2xjde                      1
4       oyt4ek                      0
..         ...                    ...
175     5qfar3                      1
176     2s2b1f                      1
177     nsd00i                      1
178     0xw93k                      0
179     2nx10r                      0

[180 rows x 2 columns]

In [4]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   patient_id                            180 non-null    object 
 1   slope_of_peak_exercise_st_segment     180 non-null    int64  
 2   thal                                  180 non-null    object 
 3   resting_blood_pressure                180 non-null    int64  
 4   chest_pain_type                       180 non-null    int64  
 5   num_major_vessels                     180 non-null    int64  
 6   fasting_blood_sugar_gt_120_mg_per_dl  180 non-null    int64  
 7   resting_ekg_results                   180 non-null    int64  
 8   serum_cholesterol_mg_per_dl           180 non-null    int64  
 9   oldpeak_eq_st_depression              180 non-null    float64
 10  sex                                   180 non-null    int64  
 11  age                

In [5]:
output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   patient_id             180 non-null    object
 1   heart_disease_present  180 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 2.9+ KB


In [6]:
input_data.isnull().sum()

patient_id                              0
slope_of_peak_exercise_st_segment       0
thal                                    0
resting_blood_pressure                  0
chest_pain_type                         0
num_major_vessels                       0
fasting_blood_sugar_gt_120_mg_per_dl    0
resting_ekg_results                     0
serum_cholesterol_mg_per_dl             0
oldpeak_eq_st_depression                0
sex                                     0
age                                     0
max_heart_rate_achieved                 0
exercise_induced_angina                 0
dtype: int64

In [7]:
input_data.patient_id.nunique()

180

In [8]:
input_data.describe()

slope_of_peak_exercise_st_segment  resting_blood_pressure  \
count                         180.000000              180.000000   
mean                            1.550000              131.311111   
std                             0.618838               17.010443   
min                             1.000000               94.000000   
25%                             1.000000              120.000000   
50%                             1.000000              130.000000   
75%                             2.000000              140.000000   
max                             3.000000              180.000000   

       chest_pain_type  num_major_vessels  \
count       180.000000         180.000000   
mean          3.155556           0.694444   
std           0.938454           0.969347   
min           1.000000           0.000000   
25%           3.000000           0.000000   
50%           3.000000           0.000000   
75%           4.000000           1.000000   
max           4.000000           3.000000   

       fasting_blood_sugar_gt_120_mg_per_dl  resting_ekg_results  \
count                            180.000000           180.000000   
mean                               0.161111             1.050000   
std                                0.368659             0.998742   
min                                0.000000             0.000000   
25%                                0.000000             0.000000   
50%                                0.000000             2.000000   
75%                                0.000000             2.000000   
max                                1.000000             2.000000   

       serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression         sex  \
count                   180.000000                180.000000  180.000000   
mean                    249.211111                  1.010000    0.688889   
std                      52.717969                  1.121357    0.464239   
min                     126.000000                  0.000000    0.000000   
25%                     213.750000                  0.000000    0.000000   
50%                     245.500000                  0.800000    1.000000   
75%                     281.250000                  1.600000    1.000000   
max                     564.000000                  6.200000    1.000000   

              age  max_heart_rate_achieved  exercise_induced_angina  
count  180.000000               180.000000               180.000000  
mean    54.811111               149.483333                 0.316667  
std      9.334737                22.063513                 0.466474  
min     29.000000                96.000000                 0.000000  
25%     48.000000               132.000000                 0.000000  
50%     55.000000               152.000000                 0.000000  
75%     62.000000               166.250000                 1.000000  
max     77.000000               202.000000                 1.000000

In [9]:
input_data.thal.unique()

array(['normal', 'reversible_defect', 'fixed_defect'], dtype=object)

In [10]:
input_data['thal'].replace(['normal', 'reversible_defect', 'fixed_defect'],
                        [0, 1,2], inplace=True)

C:\Users\Tnluser\AppData\Local\Temp\ipykernel_12940\3500095113.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  input_data['thal'].replace(['normal', 'reversible_defect', 'fixed_defect'],
C:\Users\Tnluser\AppData\Local\Temp\ipykernel_12940\3500095113.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', Tru

In [11]:
input_data.head(5)

patient_id  slope_of_peak_exercise_st_segment  thal  resting_blood_pressure  \
0     0z64un                                  1     0                     128   
1     ryoo3j                                  2     0                     110   
2     yt1s1x                                  1     0                     125   
3     l2xjde                                  1     1                     152   
4     oyt4ek                                  3     1                     178   

   chest_pain_type  num_major_vessels  fasting_blood_sugar_gt_120_mg_per_dl  \
0                2                  0                                     0   
1                3                  0                                     0   
2                4                  3                                     0   
3                4                  0                                     0   
4                1                  0                                     0   

   resting_ekg_results  serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression  \
0                    2                          308                       0.0   
1                    0                          214                       1.6   
2                    2                          304                       0.0   
3                    0                          223                       0.0   
4                    2                          270                       4.2   

   sex  age  max_heart_rate_achieved  exercise_induced_angina  
0    1   45                      170                        0  
1    0   54                      158                        0  
2    1   77                      162                        1  
3    1   40                      181                        0  
4    1   59                      145                        0

#### Splitting the Data into Train and Test

In [13]:
X = input_data.drop(columns = 'patient_id', axis=1)

In [14]:
Y = output.drop(columns= 'patient_id', axis=1)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify = Y , random_state= 2)

#### Scaling (StandardScale)

In [17]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Fit scaler to training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
!pip install xgboost

## Training 10 Models With Different Metrics

In [20]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
# Define a list of classifiers
classifiers = [
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    GaussianNB(),
    XGBClassifier()
]

In [22]:
# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, Y_train)
    y_pred = clf.predict(X_test_scaled)

    # Calculate accuracy
    accuracy = accuracy_score(Y_test, y_pred)
    print(f"{clf_name} Accuracy: {accuracy}")

    # Classification report
    print(f"Classification Report for {clf_name}:")
    print(classification_report(Y_test, y_pred))

    # Confusion matrix
    print(f"Confusion Matrix for {clf_name}:")
    print(confusion_matrix(Y_test, y_pred))
    print("="*50)

C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier Accuracy: 0.7222222222222222
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

           0       0.78      0.70      0.74        20
           1       0.67      0.75      0.71        16

    accuracy                           0.72        36
   macro avg       0.72      0.72      0.72        36
weighted avg       0.73      0.72      0.72        36

Confusion Matrix for RandomForestClassifier:
[[14  6]
 [ 4 12]]
AdaBoostClassifier Accuracy: 0.6944444444444444
Classification Report for AdaBoostClassifier:
              precision    recall  f1-score   support

           0       0.74      0.70      0.72        20
           1       0.65      0.69      0.67        16

    accuracy                           0.69        36
   macro avg       0.69      0.69      0.69        36
weighted avg       0.70      0.69      0.70        36

Confusion Matrix for AdaBoostClassifier:
[[14  6]
 [ 5 11]]


C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier Accuracy: 0.7222222222222222
Classification Report for GradientBoostingClassifier:
              precision    recall  f1-score   support

           0       0.75      0.75      0.75        20
           1       0.69      0.69      0.69        16

    accuracy                           0.72        36
   macro avg       0.72      0.72      0.72        36
weighted avg       0.72      0.72      0.72        36

Confusion Matrix for GradientBoostingClassifier:
[[15  5]
 [ 5 11]]
LogisticRegression Accuracy: 0.8888888888888888
Classification Report for LogisticRegression:
              precision    recall  f1-score   support

           0       0.86      0.95      0.90        20
           1       0.93      0.81      0.87        16

    accuracy                           0.89        36
   macro avg       0.90      0.88      0.89        36
weighted avg       0.89      0.89      0.89        36

Confusion Matrix for LogisticRegression:
[[19  1]
 [ 3 13]]
SVC Accuracy: 

C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y w

XGBClassifier Accuracy: 0.6944444444444444
Classification Report for XGBClassifier:
              precision    recall  f1-score   support

           0       0.74      0.70      0.72        20
           1       0.65      0.69      0.67        16

    accuracy                           0.69        36
   macro avg       0.69      0.69      0.69        36
weighted avg       0.70      0.69      0.70        36

Confusion Matrix for XGBClassifier:
[[14  6]
 [ 5 11]]


In [53]:
# Create a DataFrame to store the results
results_df= {}

results_df = pd.DataFrame(columns=['Model', 'Accuracy', 'F1-Score', 'Precision', 'Recall'])

In [69]:
# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, Y_train)
    y_pred = clf.predict(X_test_scaled)
    
    # Calculate evaluation metrics
    accuracy = accuracy_score(Y_test, y_pred)
    report = classification_report(Y_test, y_pred, output_dict=True)
    f1_score = report['weighted avg']['f1-score']
    precision = report['weighted avg']['precision']
    recall = report['weighted avg']['recall']
    
    # Append results to DataFrame
    results_df.loc[len(results_df)]={'Model': clf_name, 'Accuracy': accuracy, 'F1-Score': f1_score, 
                                    'Precision': precision, 'Recall': recall}

results_df

C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed whe

Model  Accuracy  F1-Score  Precision    Recall
0      RandomForestClassifier  0.833333  0.833333   0.833333  0.833333
1          AdaBoostClassifier  0.694444  0.695157   0.696938  0.694444
2  GradientBoostingClassifier  0.722222  0.722222   0.722222  0.722222
3          LogisticRegression  0.888889  0.887831   0.892496  0.888889
4                         SVC  0.777778  0.775661   0.778499  0.777778
5        KNeighborsClassifier  0.805556  0.804791   0.805291  0.805556
6      DecisionTreeClassifier  0.722222  0.719642   0.759019  0.722222
7                  GaussianNB  0.888889  0.887831   0.892496  0.888889
8               XGBClassifier  0.694444  0.695157   0.696938  0.694444

#### Best Model

In [82]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Instantiate the RandomForestClassifier
lr_classifier = LogisticRegression()

# Train the RandomForestClassifier
lr_classifier.fit(X_train_scaled, Y_train)

# Predict on the test set
y_pred_lr = lr_classifier.predict(X_test_scaled)

# Calculate accuracy
accuracy_lr = accuracy_score(Y_test, y_pred_lr)
print("Logistic Regression Accuracy:", accuracy_lr)

# Classification report
print("Classification Report for Logistic Regression:")
print(classification_report(Y_test, y_pred_lr))

# Confusion matrix
print("Confusion Matrix for Logistic Regression:")
print(confusion_matrix(Y_test, y_pred_lr))

Logistic Regression Accuracy: 0.8888888888888888
Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.86      0.95      0.90        20
           1       0.93      0.81      0.87        16

    accuracy                           0.89        36
   macro avg       0.90      0.88      0.89        36
weighted avg       0.89      0.89      0.89        36

Confusion Matrix for Logistic Regression:
[[19  1]
 [ 3 13]]


C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


#### Save Models

In [87]:
import pickle

pickle.dump(lr_classifier,open("lr_classifier.pkl",'wb'))
pickle.dump(scaler,open("scaler.pkl",'wb'))

#### Load models to test1

In [90]:

import pickle

# Load the Logistic Regression model
with open("lr_classifier.pkl", "rb") as file:
    lr_classifier = pickle.load(file)

# Load the scaler
with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

#### Prediction

In [98]:

import numpy as np
def predict(model, scaler, slope_of_peak_exercise_st_segment, thal, resting_blood_pressure, chest_pain_type,num_major_vessels,	fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina):

    # Encode categorical variables
    sex_encoded = 1 if sex.lower() == "male" else 0
    fasting_blood_sugar_gt_120_mg_per_dl_encoded = 1 if fasting_blood_sugar_gt_120_mg_per_dl.lower() == "yes" else 0
    exercise_induced_angina_encoded = 1 if exercise_induced_angina.lower() == "yes" else 0
    
    
    # Prepare features array
    features = np.array([[slope_of_peak_exercise_st_segment, thal, resting_blood_pressure, chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl_encoded,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex_encoded,age,max_heart_rate_achieved,exercise_induced_angina_encoded]])
    
    # scalling
    scaled_features = scaler.transform(features)
    
    # predict by model
    result = model.predict(scaled_features)
    
    return result[0]

#### Testing:

In [108]:
slope_of_peak_exercise_st_segment= 2
thal= 0
resting_blood_pressure= 110
chest_pain_type= 3
num_major_vessels= 0
fasting_blood_sugar_gt_120_mg_per_dl_encoded= "no"
resting_ekg_results= 0
serum_cholesterol_mg_per_dl= 214
oldpeak_eq_st_depression= 1.6
sex_encoded= "female"
age= 54
max_heart_rate_achieved= 158
exercise_induced_angina_encoded= "no"

result = predict(lr_classifier, scaler, slope_of_peak_exercise_st_segment, thal, resting_blood_pressure, chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl_encoded,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex_encoded,age,max_heart_rate_achieved,exercise_induced_angina_encoded)


if result == 1:
    print("The Patient has Heart Disease")
else: 
    print("The Patient has No Heart Disease")

The Patient has No Heart Deseas


C:\Users\Tnluser\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
